// <auto-generated>
// Do not edit this file yourself!
//
// This code was generated by Stride Shader Mixin Code Generator.
// To generate it yourself, please install Stride.VisualStudio.Package .vsix
// and re-save the associated .sdfx.
// </auto-generated>

using System;
using Stride.Core;
using Stride.Rendering;
using Stride.Graphics;
using Stride.Shaders;
using Stride.Core.Mathematics;
using Buffer = Stride.Graphics.Buffer;

namespace Stride.Rendering
{
    public static partial class SelectionWireframeShaderKeys
    {
        public static readonly ValueParameterKey<float> LineWidth = ParameterKeys.NewValue<float>();
        public static readonly ValueParameterKey<Vector4> LineColor = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Matrix> WorldViewProjection = ParameterKeys.NewValue<Matrix>();
        public static readonly ValueParameterKey<Vector4> Viewport = ParameterKeys.NewValue<Vector4>();
        public static readonly ValueParameterKey<Vector3> WorldScale = ParameterKeys.NewValue<Vector3>();
    }
}
